/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace Auction {
      
    export type AuctionItemStruct = {id: BigNumberish, name: string, description: string, imageUrl: string, startingPrice: BigNumberish, currentPrice: BigNumberish, endTime: BigNumberish, seller: AddressLike, highestBidder: AddressLike, isCompleted: boolean}

    export type AuctionItemStructOutput = [id: bigint, name: string, description: string, imageUrl: string, startingPrice: bigint, currentPrice: bigint, endTime: bigint, seller: string, highestBidder: string, isCompleted: boolean] & {id: bigint, name: string, description: string, imageUrl: string, startingPrice: bigint, currentPrice: bigint, endTime: bigint, seller: string, highestBidder: string, isCompleted: boolean }
  

    export type BidStruct = {bidder: AddressLike, amount: BigNumberish, timestamp: BigNumberish}

    export type BidStructOutput = [bidder: string, amount: bigint, timestamp: bigint] & {bidder: string, amount: bigint, timestamp: bigint }
  
    }

  export interface AuctionInterface extends Interface {
    getFunction(nameOrSignature: "auctionBids" | "auctionCounter" | "auctions" | "createAuction" | "endAuction" | "getAllActiveAuctions" | "getAuction" | "getAuctionBids" | "getCompletedAuctions" | "getPendingReturn" | "getWaitingEndAuctions" | "owner" | "pendingReturns" | "placeBid" | "platformFeePercent" | "updatePlatformFee" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuctionCreated" | "AuctionEnded" | "BidPlaced" | "FundsWithdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'auctionBids', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'auctionCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'auctions', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createAuction', values: [string, string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'endAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllActiveAuctions', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAuctionBids', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCompletedAuctions', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPendingReturn', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getWaitingEndAuctions', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingReturns', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'placeBid', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'platformFeePercent', values?: undefined): string;
encodeFunctionData(functionFragment: 'updatePlatformFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'auctionBids', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auctionCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllActiveAuctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAuctionBids', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCompletedAuctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingReturn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWaitingEndAuctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingReturns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFeePercent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePlatformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace AuctionCreatedEvent {
      export type InputTuple = [auctionId: BigNumberish, name: string, startingPrice: BigNumberish, endTime: BigNumberish];
      export type OutputTuple = [auctionId: bigint, name: string, startingPrice: bigint, endTime: bigint];
      export interface OutputObject {auctionId: bigint, name: string, startingPrice: bigint, endTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuctionEndedEvent {
      export type InputTuple = [auctionId: BigNumberish, winner: AddressLike, finalPrice: BigNumberish];
      export type OutputTuple = [auctionId: bigint, winner: string, finalPrice: bigint];
      export interface OutputObject {auctionId: bigint, winner: string, finalPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BidPlacedEvent {
      export type InputTuple = [auctionId: BigNumberish, bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [auctionId: bigint, bidder: string, amount: bigint];
      export interface OutputObject {auctionId: bigint, bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsWithdrawnEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Auction extends BaseContract {
    
    connect(runner?: ContractRunner | null): Auction;
    waitForDeployment(): Promise<this>;

    interface: AuctionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    auctionBids: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, bigint, bigint] & {bidder: string, amount: bigint, timestamp: bigint }],
      'view'
    >
    

    
    auctionCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    auctions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, string, string, boolean] & {id: bigint, name: string, description: string, imageUrl: string, startingPrice: bigint, currentPrice: bigint, endTime: bigint, seller: string, highestBidder: string, isCompleted: boolean }],
      'view'
    >
    

    
    createAuction: TypedContractMethod<
      [_name: string, _description: string, _imageUrl: string, _startingPrice: BigNumberish, _duration: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    endAuction: TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAllActiveAuctions: TypedContractMethod<
      [],
      [Auction.AuctionItemStructOutput[]],
      'view'
    >
    

    
    getAuction: TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [Auction.AuctionItemStructOutput],
      'view'
    >
    

    
    getAuctionBids: TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [Auction.BidStructOutput[]],
      'view'
    >
    

    
    getCompletedAuctions: TypedContractMethod<
      [],
      [Auction.AuctionItemStructOutput[]],
      'view'
    >
    

    
    getPendingReturn: TypedContractMethod<
      [_auctionId: BigNumberish, _user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getWaitingEndAuctions: TypedContractMethod<
      [],
      [Auction.AuctionItemStructOutput[]],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingReturns: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    placeBid: TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    platformFeePercent: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    updatePlatformFee: TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'auctionBids'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[string, bigint, bigint] & {bidder: string, amount: bigint, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'auctionCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'auctions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, string, string, boolean] & {id: bigint, name: string, description: string, imageUrl: string, startingPrice: bigint, currentPrice: bigint, endTime: bigint, seller: string, highestBidder: string, isCompleted: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'createAuction'): TypedContractMethod<
      [_name: string, _description: string, _imageUrl: string, _startingPrice: BigNumberish, _duration: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endAuction'): TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllActiveAuctions'): TypedContractMethod<
      [],
      [Auction.AuctionItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAuction'): TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [Auction.AuctionItemStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getAuctionBids'): TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [Auction.BidStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getCompletedAuctions'): TypedContractMethod<
      [],
      [Auction.AuctionItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingReturn'): TypedContractMethod<
      [_auctionId: BigNumberish, _user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getWaitingEndAuctions'): TypedContractMethod<
      [],
      [Auction.AuctionItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingReturns'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'placeBid'): TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'platformFeePercent'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'updatePlatformFee'): TypedContractMethod<
      [_newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [_auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AuctionCreated'): TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
getEvent(key: 'AuctionEnded'): TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
getEvent(key: 'BidPlaced'): TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
getEvent(key: 'FundsWithdrawn'): TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;

    filters: {
      
      'AuctionCreated(uint256,string,uint256,uint256)': TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
      AuctionCreated: TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
    

      'AuctionEnded(uint256,address,uint256)': TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
      AuctionEnded: TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
    

      'BidPlaced(uint256,address,uint256)': TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
      BidPlaced: TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
    

      'FundsWithdrawn(address,uint256)': TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
      FundsWithdrawn: TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
    
    };
  }