/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as auctionSol from './Auction.sol/index.js';
export * as counterSol from './Counter.sol/index.js';
export * as myTokenSol from './MyToken.sol/index.js';