/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface AuctionInterface extends Interface {
    getFunction(nameOrSignature: "bid" | "endAuction" | "endTime" | "ended" | "highestBid" | "highestBidder" | "itemName" | "owner" | "pendingReturns" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuctionEnded" | "HighestBidIncreased"): EventFragment;

    encodeFunctionData(functionFragment: 'bid', values?: undefined): string;
encodeFunctionData(functionFragment: 'endAuction', values?: undefined): string;
encodeFunctionData(functionFragment: 'endTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'ended', values?: undefined): string;
encodeFunctionData(functionFragment: 'highestBid', values?: undefined): string;
encodeFunctionData(functionFragment: 'highestBidder', values?: undefined): string;
encodeFunctionData(functionFragment: 'itemName', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingReturns', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'bid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ended', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'highestBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'highestBidder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'itemName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingReturns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace AuctionEndedEvent {
      export type InputTuple = [winner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [winner: string, amount: bigint];
      export interface OutputObject {winner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HighestBidIncreasedEvent {
      export type InputTuple = [bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [bidder: string, amount: bigint];
      export interface OutputObject {bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Auction extends BaseContract {
    
    connect(runner?: ContractRunner | null): Auction;
    waitForDeployment(): Promise<this>;

    interface: AuctionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bid: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    endAuction: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    endTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ended: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    highestBid: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    highestBidder: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    itemName: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingReturns: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bid'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'endAuction'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ended'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'highestBid'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'highestBidder'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'itemName'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingReturns'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'AuctionEnded'): TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
getEvent(key: 'HighestBidIncreased'): TypedContractEvent<HighestBidIncreasedEvent.InputTuple, HighestBidIncreasedEvent.OutputTuple, HighestBidIncreasedEvent.OutputObject>;

    filters: {
      
      'AuctionEnded(address,uint256)': TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
      AuctionEnded: TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
    

      'HighestBidIncreased(address,uint256)': TypedContractEvent<HighestBidIncreasedEvent.InputTuple, HighestBidIncreasedEvent.OutputTuple, HighestBidIncreasedEvent.OutputObject>;
      HighestBidIncreased: TypedContractEvent<HighestBidIncreasedEvent.InputTuple, HighestBidIncreasedEvent.OutputTuple, HighestBidIncreasedEvent.OutputObject>;
    
    };
  }