/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auctionSol from './Auction.sol/index.js';
export type { auctionSol };
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as myTokenSol from './MyToken.sol/index.js';
export type { myTokenSol };
export * as factories from './factories/index.js';
export type { Auction } from './Auction.sol/Auction.js';
export { Auction__factory } from './factories/Auction.sol/Auction__factory.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { MyToken } from './MyToken.sol/MyToken.js';
export { MyToken__factory } from './factories/MyToken.sol/MyToken__factory.js';